import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Image from "next/image";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["200", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Sanket Lamsal</title>
      </head>
      <body
        className={`${popins.className} flex min-h-screen flex-col items-center justify-center bg-backgroundColor `}>
        <div className="relative z-10 h-[85vh] w-[80vw] rounded-3xl bg-glass px-20 pt-5 text-white backdrop-blur-lg">
          <Navbar />
          {children}
        </div>
        <img src="/donut.png" className="absolute bottom-0 right-0 z-0" alt="Imag of a donut 3d"/>
      </body>
    </html>
  );
}
